/**
 * Service worker -- offline play.
 *
 * GENERATED by tools/make_sw.py; do not edit by hand. The cache name carries a
 * hash of every precached file, so a rebuild invalidates the old cache instead
 * of leaving players on a stale mix of new code and old models.
 */

const CACHE = 'asfalt-firtinasi-920c515572b9';
const ASSETS = [
  "./",
  "assets/icon-192.png",
  "assets/icon-512.png",
  "assets/icon.svg",
  "assets/models/barrier.glb",
  "assets/models/beacon.glb",
  "assets/models/billboard.glb",
  "assets/models/block_downtown.glb",
  "assets/models/block_industrial.glb",
  "assets/models/block_lowrise.glb",
  "assets/models/block_park.glb",
  "assets/models/block_parking.glb",
  "assets/models/cactus.glb",
  "assets/models/car_muscle.glb",
  "assets/models/car_sport.glb",
  "assets/models/car_super.glb",
  "assets/models/city_ground.glb",
  "assets/models/city_wall.glb",
  "assets/models/coin.glb",
  "assets/models/cone.glb",
  "assets/models/desert_floor.glb",
  "assets/models/ground.glb",
  "assets/models/guardrail.glb",
  "assets/models/lamp.glb",
  "assets/models/manifest.json",
  "assets/models/mesa.glb",
  "assets/models/nitro.glb",
  "assets/models/palm.glb",
  "assets/models/pedestrian.glb",
  "assets/models/road.glb",
  "assets/models/rock.glb",
  "assets/models/traffic_bus.glb",
  "assets/models/traffic_hatch.glb",
  "assets/models/traffic_light.glb",
  "assets/models/traffic_sedan.glb",
  "assets/models/traffic_suv.glb",
  "assets/models/traffic_truck.glb",
  "css/style.css",
  "index.html",
  "js/assets.js",
  "js/audio.js",
  "js/car.js",
  "js/city.js",
  "js/config.js",
  "js/environment.js",
  "js/garage.js",
  "js/highway.js",
  "js/hud.js",
  "js/input.js",
  "js/main.js",
  "js/minimap.js",
  "js/pedestrians.js",
  "js/pickups.js",
  "js/player.js",
  "js/save.js",
  "js/signals.js",
  "js/traffic.js",
  "js/world.js",
  "manifest.webmanifest",
  "vendor/three/addons/loaders/GLTFLoader.js",
  "vendor/three/addons/utils/BufferGeometryUtils.js",
  "vendor/three/three.core.min.js",
  "vendor/three/three.module.min.js"
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(ASSETS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Cache-first: everything here is versioned by the cache name above.
  event.respondWith(
    caches.match(request).then((hit) => hit || fetch(request).then((response) => {
      if (response && response.ok && response.type === 'basic') {
        const copy = response.clone();
        caches.open(CACHE).then((cache) => cache.put(request, copy));
      }
      return response;
    }).catch(() => caches.match('index.html')))
  );
});
