/* generated by tools/make_sw.py -- do not edit */
const CACHE = 'sicra-b8e9cd6b82e5';
const FILES = [
  "./assets/icon-192.png",
  "./assets/icon-512.png",
  "./assets/icon.svg",
  "./css/style.css",
  "./dist/assets/icon-192.png",
  "./dist/assets/icon-512.png",
  "./dist/assets/icon.svg",
  "./dist/css/style.css",
  "./dist/index.html",
  "./dist/js/audio.js",
  "./dist/js/chaser.js",
  "./dist/js/config.js",
  "./dist/js/effects.js",
  "./dist/js/figure.js",
  "./dist/js/haptics.js",
  "./dist/js/hud.js",
  "./dist/js/i18n.js",
  "./dist/js/input.js",
  "./dist/js/main.js",
  "./dist/js/missions.js",
  "./dist/js/player.js",
  "./dist/js/quality.js",
  "./dist/js/rng.js",
  "./dist/js/save.js",
  "./dist/js/track.js",
  "./dist/js/ui.js",
  "./dist/js/world.js",
  "./dist/manifest.webmanifest",
  "./dist/vendor/three/three.core.min.js",
  "./dist/vendor/three/three.module.min.js",
  "./",
  "./js/audio.js",
  "./js/chaser.js",
  "./js/config.js",
  "./js/effects.js",
  "./js/figure.js",
  "./js/haptics.js",
  "./js/hud.js",
  "./js/i18n.js",
  "./js/input.js",
  "./js/main.js",
  "./js/missions.js",
  "./js/player.js",
  "./js/quality.js",
  "./js/rng.js",
  "./js/save.js",
  "./js/track.js",
  "./js/ui.js",
  "./js/world.js",
  "./manifest.webmanifest",
  "./vendor/three/three.core.min.js",
  "./vendor/three/three.module.min.js"
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(caches.keys().then((keys) =>
    Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
  ).then(() => self.clients.claim()));
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  event.respondWith(caches.match(event.request, { ignoreSearch: true }).then((hit) =>
    hit || fetch(event.request).then((res) => {
      const copy = res.clone();
      caches.open(CACHE).then((c) => c.put(event.request, copy));
      return res;
    }).catch(() => hit)
  ));
});
