"""
kit.py -- low-poly modelling toolkit built on Blender's Python API (bpy).

Everything the game renders is generated by these helpers: no external asset
is downloaded or hand-modelled. Meshes are built from explicit vertex data so
the output is deterministic and the triangle budget stays phone-friendly.

Axis convention (important):
    +Y = vehicle forward          (glTF export maps Blender +Y -> glTF -Z,
    +X = vehicle right             which is "forward" for three.js cameras)
    +Z = up                        so models arrive correctly oriented.
"""

import math
import os

import bpy


# --------------------------------------------------------------------------- #
# scene housekeeping
# --------------------------------------------------------------------------- #

def reset():
    """Start from a completely empty scene and drop orphaned datablocks."""
    bpy.ops.wm.read_factory_settings(use_empty=True)
    for collection in (bpy.data.objects, bpy.data.meshes,
                       bpy.data.materials, bpy.data.curves):
        for item in list(collection):
            try:
                collection.remove(item)
            except RuntimeError:
                pass


def activate(obj):
    """Make `obj` the sole selected + active object (required by bpy.ops)."""
    for other in bpy.context.selected_objects:
        other.select_set(False)
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj


# --------------------------------------------------------------------------- #
# materials
# --------------------------------------------------------------------------- #

def _principled(material):
    for node in material.node_tree.nodes:
        if node.type == 'BSDF_PRINCIPLED':
            return node
    return None


def _plug(node, key, value):
    """Set a shader input only if this Blender version exposes it."""
    if node is not None and key in node.inputs:
        node.inputs[key].default_value = value


def mat(name, color, metallic=0.0, roughness=0.5,
        emission=None, emission_strength=4.0):
    """Create (or reuse) a Principled material. `color` is linear RGB 0..1."""
    existing = bpy.data.materials.get(name)
    if existing is not None:
        return existing

    material = bpy.data.materials.new(name)
    material.use_nodes = True
    node = _principled(material)
    _plug(node, 'Base Color', (*color, 1.0))
    _plug(node, 'Metallic', metallic)
    _plug(node, 'Roughness', roughness)
    if emission is not None:
        _plug(node, 'Emission Color', (*emission, 1.0))
        _plug(node, 'Emission Strength', emission_strength)
    material.diffuse_color = (*color, 1.0)          # solid-view / fallback
    return material


# --------------------------------------------------------------------------- #
# mesh construction
# --------------------------------------------------------------------------- #

def mesh_from(name, verts, faces, material=None, location=(0, 0, 0),
              materials=None, face_mats=None):
    """
    Build an object from raw vertex/face lists, normals recalculated outward.

    `materials` is an ordered slot list and `face_mats` a per-face slot index,
    which is how a single body mesh carries paint, glass and trim at once.
    """
    mesh = bpy.data.meshes.new(name)
    mesh.from_pydata(verts, [], faces)
    mesh.validate()
    mesh.update()
    for polygon in mesh.polygons:
        polygon.use_smooth = False                  # low-poly = flat shading

    obj = bpy.data.objects.new(name, mesh)
    obj.location = location
    bpy.context.collection.objects.link(obj)

    for slot in (materials if materials is not None else
                 ([material] if material is not None else [])):
        obj.data.materials.append(slot)

    if face_mats is not None and len(mesh.polygons) == len(face_mats):
        for polygon, index in zip(mesh.polygons, face_mats):
            polygon.material_index = index

    activate(obj)
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.normals_make_consistent(inside=False)
    bpy.ops.object.mode_set(mode='OBJECT')
    return obj


def section(y, w, z0, z1, bw=None, tw=None, zm=None, zb=None):
    """
    One cross-section of a lofted body, described in the X-Z plane at `y`.

        w   half-width of the body side       bw  half-width at the floor
        z0  floor height                      tw  half-width at the roof
        z1  roof height                       zm  height of the widest point
        zb  beltline height (where the glass starts)

    Narrowing the floor (`bw`) carves out the space the wheels sit in, and the
    beltline splits each flank into a painted lower panel and a window band.
    """
    span = max(z1 - z0, 1e-4)
    return {
        'y': y, 'w': w, 'z0': z0, 'z1': z1,
        'bw': w * 0.72 if bw is None else bw,
        'tw': w * 0.88 if tw is None else tw,
        'zm': z0 + span * 0.42 if zm is None else zm,
        'zb': z1 - span * 0.06 if zb is None else zb,
    }


def _section_points(s):
    """
    Eight points tracing the section outline, ordered so that the quad bands
    bridging two sections always have the same meaning:

        0 floor   1 lower flank R   2 flank R   3 window band R
        4 roof    5 window band L   6 flank L   7 lower flank L
    """
    zb = min(max(s['zb'], s['zm'] + 1e-3), s['z1'])
    return [
        (-s['bw'], s['z0']), (s['bw'], s['z0']),
        (s['w'], s['zm']), (s['w'], zb),
        (s['tw'], s['z1']), (-s['tw'], s['z1']),
        (-s['w'], zb), (-s['w'], s['zm']),
    ]


# Band indices produced by loft(), named for readability by callers.
BAND_FLOOR, BAND_LOWER_R, BAND_FLANK_R, BAND_WINDOW_R = 0, 1, 2, 3
BAND_ROOF, BAND_WINDOW_L, BAND_FLANK_L, BAND_LOWER_L = 4, 5, 6, 7


def loft(name, sections, material=None, bevel=0.0, location=(0, 0, 0),
         materials=None, face_material=None):
    """
    Bridge a series of cross-sections into a closed solid.

    `face_material(i, band)` -> slot index is called for every quad bridging
    section `i` and `i + 1`; caps are asked for with band=None.
    """
    ring = len(_section_points(sections[0]))
    verts, faces, face_mats = [], [], []

    for s in sections:
        for (x, z) in _section_points(s):
            verts.append((x, s['y'], z))

    for i in range(len(sections) - 1):
        a, b = i * ring, (i + 1) * ring
        for k in range(ring):
            k2 = (k + 1) % ring
            faces.append((a + k, a + k2, b + k2, b + k))
            face_mats.append(0 if face_material is None
                             else face_material(i, k))

    faces.append(tuple(range(ring)))                                  # rear cap
    tail = (len(sections) - 1) * ring
    faces.append(tuple(range(tail, tail + ring)))                     # nose cap
    for _ in range(2):
        face_mats.append(0 if face_material is None
                         else face_material(None, None))

    obj = mesh_from(name, verts, faces, material, location,
                    materials=materials,
                    face_mats=face_mats if materials else None)
    if bevel > 0:
        add_bevel(obj, bevel)
    return obj


def box(name, size, location=(0, 0, 0), material=None, bevel=0.0,
        taper=1.0, shear=0.0):
    """
    Axis-aligned box centred on its own origin.

    `taper` scales the top face (a value below 1 gives a truncated pyramid,
    which is how the buildings and mesas get their silhouette) and `shear`
    slides the top face along +Y.
    """
    sx, sy, sz = (d / 2.0 for d in size)
    tx, ty = sx * taper, sy * taper
    verts = [
        (-sx, -sy, -sz), (sx, -sy, -sz), (sx, sy, -sz), (-sx, sy, -sz),
        (-tx, -ty + shear, sz), (tx, -ty + shear, sz),
        (tx, ty + shear, sz), (-tx, ty + shear, sz),
    ]
    faces = [(0, 1, 2, 3), (4, 5, 6, 7), (0, 1, 5, 4),
             (1, 2, 6, 5), (2, 3, 7, 6), (3, 0, 4, 7)]
    obj = mesh_from(name, verts, faces, material, location)
    if bevel > 0:
        add_bevel(obj, bevel)
    return obj


def plate(name, size, location=(0, 0, 0), material=None):
    """
    Flat quad lying in the ground plane: two triangles where a box costs
    twelve.

    Road markings are paint on asphalt -- they have no thickness to show, and
    a city's worth of them is the single biggest triangle bill in the scene,
    so they are built as quads rather than as very thin boxes.
    """
    sx, sy = size[0] / 2.0, size[1] / 2.0
    verts = [(-sx, -sy, 0.0), (sx, -sy, 0.0), (sx, sy, 0.0), (-sx, sy, 0.0)]
    return mesh_from(name, verts, [(0, 1, 2, 3)], material, location)


def cylinder(name, radius, depth, axis='Z', location=(0, 0, 0), segments=16,
             material=None, radius_top=None):
    """Capped cylinder / cone frustum aligned to `axis`."""
    r_top = radius if radius_top is None else radius_top
    half = depth / 2.0
    verts, faces = [], []

    for level, (r, offset) in enumerate(((radius, -half), (r_top, half))):
        for i in range(segments):
            angle = 2 * math.pi * i / segments
            u, v = math.cos(angle) * r, math.sin(angle) * r
            if axis == 'X':
                verts.append((offset, u, v))
            elif axis == 'Y':
                verts.append((u, offset, v))
            else:
                verts.append((u, v, offset))

    for i in range(segments):
        j = (i + 1) % segments
        faces.append((i, j, segments + j, segments + i))
    faces.append(tuple(range(segments - 1, -1, -1)))
    faces.append(tuple(range(segments, segments * 2)))

    return mesh_from(name, verts, faces, material, location)


def add_bevel(obj, width, segments=2, angle=40.0):
    """Bevel + apply, so exported geometry needs no modifier support."""
    modifier = obj.modifiers.new('Bevel', 'BEVEL')
    modifier.width = width
    modifier.segments = segments
    modifier.limit_method = 'ANGLE'
    modifier.angle_limit = math.radians(angle)
    modifier.harden_normals = False
    activate(obj)
    bpy.ops.object.modifier_apply(modifier=modifier.name)
    for polygon in obj.data.polygons:
        polygon.use_smooth = False
    return obj


def join(objs, name):
    """Merge objects into one mesh (material slots are preserved)."""
    objs = [o for o in objs if o is not None]
    if len(objs) == 1:
        objs[0].name = name
        return objs[0]
    target = objs[0]
    activate(target)
    for other in objs[1:]:
        other.select_set(True)
    bpy.ops.object.join()
    target.name = name
    target.data.name = name
    return target


def empty(name):
    obj = bpy.data.objects.new(name, None)
    bpy.context.collection.objects.link(obj)
    return obj


def parent(child, parent_obj):
    """Parent while keeping the child's world transform (offset preserved)."""
    child.parent = parent_obj
    child.matrix_parent_inverse = parent_obj.matrix_world.inverted()
    return child


def move_origin(obj, offset):
    """Shift mesh data by `offset` so the object origin lands where we want."""
    for vert in obj.data.vertices:
        vert.co.x += offset[0]
        vert.co.y += offset[1]
        vert.co.z += offset[2]
    obj.data.update()
    return obj


# --------------------------------------------------------------------------- #
# export
# --------------------------------------------------------------------------- #

def sync():
    """Flush pending parenting/transform changes into matrix_world."""
    bpy.context.view_layer.update()


def export(path, objects=None):
    """Write a .glb. Passing `objects` exports just that selection."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    sync()

    if objects is None:
        use_selection = False
    else:
        use_selection = True
        for obj in bpy.context.selected_objects:
            obj.select_set(False)
        for obj in objects:
            obj.select_set(True)
        bpy.context.view_layer.objects.active = objects[0]

    bpy.ops.export_scene.gltf(
        filepath=path,
        export_format='GLB',
        use_selection=use_selection,
        export_apply=True,
        export_yup=True,
        export_cameras=False,
        export_lights=False,
    )
    return path


def tri_count(objs=None):
    """Triangle total, so the asset report can flag anything too heavy."""
    objs = objs or [o for o in bpy.data.objects if o.type == 'MESH']
    total = 0
    for obj in objs:
        for polygon in obj.data.polygons:
            total += max(len(polygon.vertices) - 2, 1)
    return total


def hex_color(value):
    """sRGB hex -> linear RGB, so authored colours survive the glTF round-trip."""
    value = value.lstrip('#')
    out = []
    for i in range(0, 6, 2):
        c = int(value[i:i + 2], 16) / 255.0
        out.append(c / 12.92 if c <= 0.04045
                   else ((c + 0.055) / 1.055) ** 2.4)
    return tuple(out)
