#!/usr/bin/env python3
"""
make_sw.py -- regenerate the service worker's precache list from disk.

    python3 tools/make_sw.py

The cache name is a hash of every file's content, so a new build replaces
the old cache instead of serving stale files.
"""

import hashlib
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKIP_DIRS = {'.git', 'tools', 'tests', 'node_modules', 'android', 'store', '.test-shots'}
SKIP_NAMES = {'sw.js', 'package.json', 'package-lock.json', 'README.md', 'capacitor.config.json'}
INCLUDE_EXT = {'.html', '.css', '.js', '.json', '.webmanifest', '.png', '.svg'}


def collect():
    files = []
    for base, dirs, names in os.walk(ROOT):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for name in sorted(names):
            if name in SKIP_NAMES:
                continue
            if os.path.splitext(name)[1].lower() not in INCLUDE_EXT:
                continue
            path = os.path.join(base, name)
            files.append(os.path.relpath(path, ROOT).replace(os.sep, '/'))
    return sorted(files)


def fingerprint(files):
    h = hashlib.sha1()
    for rel in files:
        h.update(rel.encode())
        with open(os.path.join(ROOT, rel), 'rb') as f:
            h.update(f.read())
    return h.hexdigest()[:12]


TEMPLATE = """/* generated by tools/make_sw.py -- do not edit */
const CACHE = 'sicra-%(hash)s';
const FILES = %(files)s;

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(caches.keys().then((keys) =>
    Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
  ).then(() => self.clients.claim()));
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  event.respondWith(caches.match(event.request, { ignoreSearch: true }).then((hit) =>
    hit || fetch(event.request).then((res) => {
      const copy = res.clone();
      caches.open(CACHE).then((c) => c.put(event.request, copy));
      return res;
    }).catch(() => hit)
  ));
});
"""


def main():
    files = collect()
    files = ['./' + f if f != 'index.html' else './' for f in files]
    if './' not in files:
        files.insert(0, './')
    content = TEMPLATE % {
        'hash': fingerprint([f[2:] if f != './' else 'index.html' for f in files]),
        'files': json.dumps(files, indent=2),
    }
    with open(os.path.join(ROOT, 'sw.js'), 'w') as f:
        f.write(content)
    print('sw.js: %d files' % len(files))


if __name__ == '__main__':
    main()
