/**
 * check.mjs -- the standards gate.
 *
 *     npm run check          every check, one line each
 *     npm run check -- -v    also list the checks that passed cleanly
 *
 * docs/ENGINEERING-STANDARDS.md says what this repository promises. This file
 * is the part of that promise a machine can keep: every rule here is one that
 * has a right answer, so nobody has to remember it during review.
 *
 * The checks are deliberately about *drift* rather than taste. A generated
 * file that no longer matches its source, a string the UI asks for and the
 * translation table does not have, a lifted element id that no longer exists
 * in the shell, a version that moved in one file and not the other -- none of
 * those show up as a broken test, and all of them reach players.
 *
 * It runs in about a second and needs no browser and no dependencies, so
 * `npm test` runs it before opening one: a typo should never cost a
 * five-minute browser run. tests/gate.test.mjs proves each check here bites.
 */

import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, normalize, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const rel = (path) => relative(ROOT, path).split('\\').join('/');
const read = (path) => readFileSync(join(ROOT, path), 'utf8');

/** Third-party or generated trees: ours to ship, not ours to hold to account. */
const NOT_OURS = [
  'game/vendor/',      // three.js, MIT, vendored verbatim
  'android/',          // Capacitor scaffolding, regenerated by `cap sync`
  'node_modules/',
];

const TEXT_SOURCE = /\.(js|mjs|py|sh|css|html|json|webmanifest|md|yml|yaml)$/;
const CODE = /\.(js|mjs|py|sh)$/;

/**
 * Every text file we are responsible for, as repo-relative paths.
 *
 * Read from git rather than walked from disk: .gitignore already knows what
 * is build output, cache and test screenshot, so this gets that for free.
 * Files that are not committed yet count too -- a rule you only find out
 * about after committing is a rule you find out about too late.
 */
function tracked() {
  const out = execFileSync(
    'git', ['ls-files', '-z', '--cached', '--others', '--exclude-standard'],
    { cwd: ROOT }).toString().split('\0').filter(Boolean);
  return [...new Set(out)]
    .filter((path) => !NOT_OURS.some((prefix) => path.startsWith(prefix)))
    .filter((path) => existsSync(join(ROOT, path)) && statSync(join(ROOT, path)).isFile())
    .sort();
}

const FILES = tracked();
const OURS = FILES.filter((path) => TEXT_SOURCE.test(path));
const SOURCE = FILES.filter((path) => CODE.test(path));
const GAME_JS = FILES.filter((path) => /^game\/js\/.+\.js$/.test(path));

/** Cache file contents: most checks want most files. */
const cache = new Map();
function text(path) {
  if (!cache.has(path)) cache.set(path, read(path));
  return cache.get(path);
}

// --- the checks -------------------------------------------------------------
// Each returns an array of complaints. Empty means the check passed, and the
// strings are what a person needs in order to go and fix it -- file and line
// wherever there is one.

const checks = [];
const check = (name, why, run) => checks.push({ name, why, run });

check('no unfinished work is left in the tree',
      'A marker is a promise to come back, and nobody does. Either the thing '
      + 'is done, or it is an issue -- not a word in a file.',
      () => {
        const marker = /\b(TODO|FIXME|XXX|HACK|WIP)\b/;
        const found = [];
        for (const path of OURS) {
          // The gate, the suite that proves the gate bites, and the standard
          // that explains it all have to write the markers down to ban them.
          if (path === 'tools/check.mjs') continue;
          if (path === 'tests/gate.test.mjs') continue;
          if (path === 'docs/ENGINEERING-STANDARDS.md') continue;
          text(path).split('\n').forEach((line, i) => {
            if (marker.test(line)) found.push(`${path}:${i + 1}: ${line.trim()}`);
          });
        }
        return found;
      });

check('no debugging is left switched on',
      'Console noise in shipped code is a broken window, and a paused test '
      + 'run is a test that never fails.',
      () => {
        const found = [];
        for (const path of GAME_JS) {
          text(path).split('\n').forEach((line, i) => {
            if (/\bconsole\.(log|debug|trace)\s*\(/.test(line)) {
              found.push(`${path}:${i + 1}: console left in shipped code`);
            }
            if (/\bdebugger\b|\balert\s*\(/.test(line)) {
              found.push(`${path}:${i + 1}: ${line.trim()}`);
            }
          });
        }
        for (const path of FILES.filter((p) => p.startsWith('tests/'))) {
          text(path).split('\n').forEach((line, i) => {
            if (/\bpage\.pause\s*\(/.test(line)) {
              found.push(`${path}:${i + 1}: page.pause() would hang the suite`);
            }
          });
        }
        return found;
      });

check('every module says what it is for',
      'The header comment is where the *why* lives. Without it the next '
      + 'reader has to infer intent from mechanism, and they get it wrong.',
      () => SOURCE.filter((path) => {
        const body = text(path).replace(/^#!.*\n/, '').trimStart();
        const opener = path.endsWith('.sh') ? ['#'] : ['/**', '"""'];
        return !opener.some((start) => body.startsWith(start));
      }).map((path) => `${path}: no header comment`));

check('the two translation tables agree',
      'A key in one language and not the other is a screen that silently '
      + 'falls back to English for half the players.',
      () => {
        const { tables, order } = i18n();
        const found = [];
        for (const [code, table] of Object.entries(tables)) {
          const seen = new Set();
          for (const key of order[code]) {
            if (seen.has(key)) found.push(`i18n: '${key}' defined twice in ${code}`);
            seen.add(key);
          }
        }
        const [a, b] = Object.keys(tables);
        for (const key of Object.keys(tables[a])) {
          if (!(key in tables[b])) found.push(`i18n: '${key}' missing from ${b}`);
        }
        for (const key of Object.keys(tables[b])) {
          if (!(key in tables[a])) found.push(`i18n: '${key}' missing from ${a}`);
        }
        // A {placeholder} that exists in one language and not the other means
        // one of them prints a number and the other drops it.
        const slots = (value) => [...value.matchAll(/\{(\w+)\}/g)]
          .map((m) => m[1]).sort().join(',');
        for (const key of Object.keys(tables[a])) {
          if (!(key in tables[b])) continue;
          if (slots(tables[a][key]) !== slots(tables[b][key])) {
            found.push(`i18n: '${key}' fills different placeholders in ${a} and ${b}`
                       + ` (${slots(tables[a][key])} vs ${slots(tables[b][key])})`);
          }
        }
        return found;
      });

check('every string is asked for, and everything asked for exists',
      'A missing key renders as the key itself; a stale one is dead weight '
      + 'a translator still has to carry.',
      () => {
        const { tables } = i18n();
        const keys = Object.keys(tables.tr);
        const found = [];
        const { asked, mentioned, prefixes } = keyReferences();

        for (const ref of asked) {
          if (!keys.includes(ref.key)) {
            found.push(`${ref.where}: asks for '${ref.key}', which no language defines`);
          }
        }
        for (const key of keys) {
          const used = mentioned.has(key)
            || prefixes.some((prefix) => prefix && key.startsWith(prefix));
          if (!used) found.push(`i18n: '${key}' is defined but nothing asks for it`);
        }
        return found;
      });

check('the offline cache matches what ships',
      'game/sw.js is generated. Edit a module without regenerating it and '
      + 'returning players keep the old build forever.',
      () => {
        try {
          execFileSync('python3', [join(ROOT, 'tools', 'make_sw.py'), '--check'],
                       { cwd: ROOT, stdio: 'pipe' });
          return [];
        } catch (err) {
          const said = (err.stdout || '').toString().trim();
          return [said || 'game/sw.js is stale -- run: npm run sw'];
        }
      });

check('models, manifest and code agree',
      'The manifest is what the game measures collisions and lanes from. A '
      + 'model missing from either side is a crash on load or dead geometry.',
      () => {
        const manifest = JSON.parse(text('game/assets/models/manifest.json'));
        const named = Object.keys(manifest.models || manifest);
        const onDisk = readdirSync(join(ROOT, 'game/assets/models'))
          .filter((name) => name.endsWith('.glb'))
          .map((name) => name.replace(/\.glb$/, ''));
        const found = [];
        for (const name of named) {
          if (!onDisk.includes(name)) {
            found.push(`manifest.json lists '${name}', but ${name}.glb is not on disk`);
          }
        }
        for (const name of onDisk) {
          if (!named.includes(name)) {
            found.push(`${name}.glb is on disk but missing from manifest.json`
                       + ' -- run: npm run assets');
          }
        }
        // Names the game loads by string literal must be ones we produced.
        const loaded = new Set();
        for (const path of GAME_JS) {
          for (const m of text(path).matchAll(/\b(?:model|glb)\(\s*'([\w_]+)'/g)) {
            loaded.add(m[1]);
          }
        }
        for (const name of loaded) {
          if (!named.includes(name)) {
            found.push(`the game loads model '${name}', which the manifest does not list`);
          }
        }
        return found;
      });

check('everything the shell points at exists',
      'A mistyped element id reads as null at runtime, usually inside a '
      + 'handler nobody runs until a player does.',
      () => {
        const html = text('game/index.html');
        const ids = new Set([...html.matchAll(/\bid="([^"]+)"/g)].map((m) => m[1]));
        const found = [];
        for (const path of GAME_JS) {
          const body = text(path);
          // Only fixed ids: `'screen-' + name` is resolved at runtime and the
          // ids it builds are checked by the browser suites instead.
          for (const m of body.matchAll(/getElementById\(\s*'([^']+)'\s*\)/g)) {
            if (!ids.has(m[1])) found.push(`${path}: no element with id '${m[1]}'`);
          }
          for (const m of body.matchAll(/querySelector\(\s*'#([\w-]+)'\s*\)/g)) {
            if (!ids.has(m[1])) found.push(`${path}: no element with id '${m[1]}'`);
          }
        }
        // Files the page and the web manifest reference.
        const refs = [
          ...[...html.matchAll(/\b(?:src|href)="(?!https?:|data:|#)([^"]+)"/g)]
            .map((m) => m[1]),
          ...[...text('game/manifest.webmanifest').matchAll(/"src":\s*"([^"]+)"/g)]
            .map((m) => m[1]),
        ];
        for (const ref of refs) {
          const path = normalize(join('game', ref.split('?')[0]));
          if (!existsSync(join(ROOT, path))) {
            found.push(`game/index.html or the web manifest points at ${ref}, which is missing`);
          }
        }
        return found;
      });

check('the app is called the same thing everywhere',
      'Version and identity live in four files that nothing links together. '
      + 'Play rejects a bundle whose id moved; players get a stuck update '
      + 'when the version did not.',
      () => {
        const pkg = JSON.parse(text('package.json'));
        const cap = JSON.parse(text('capacitor.config.json'));
        const gradle = text('android/app/build.gradle');
        const strings = text('android/app/src/main/res/values/strings.xml');
        const webManifest = JSON.parse(text('game/manifest.webmanifest'));
        const { tables } = i18n();
        const one = (source, re, label) => {
          const m = source.match(re);
          return m ? m[1] : `<${label} not found>`;
        };

        const found = [];
        const same = (what, ...values) => {
          if (new Set(values).size !== 1) found.push(`${what}: ${values.join(' vs ')}`);
        };
        same('version drifts between package.json and Android',
             pkg.version, one(gradle, /versionName\s+"([^"]+)"/, 'versionName'));
        same('app id drifts between Capacitor, Gradle and Android resources',
             cap.appId,
             one(gradle, /applicationId\s+"([^"]+)"/, 'applicationId'),
             one(gradle, /namespace\s+"([^"]+)"/, 'namespace'),
             one(strings, /name="package_name">([^<]+)</, 'package_name'));
        same('app name drifts between Capacitor, Android, the web manifest and the game',
             cap.appName,
             one(strings, /name="app_name">([^<]+)</, 'app_name'),
             webManifest.name,
             tables.tr['app.name']);
        if (!existsSync(join(ROOT, cap.webDir))) {
          found.push(`capacitor.config.json ships '${cap.webDir}', which does not exist`);
        }
        const code = one(gradle, /versionCode\s+(\d+)/, 'versionCode');
        if (!/^\d+$/.test(code)) found.push('android/app/build.gradle has no versionCode');
        return found;
      });

check('no module is stranded',
      'A file nothing imports is either dead code or a feature that silently '
      + 'stopped shipping. Both are worth knowing about.',
      () => {
        const html = text('game/index.html');
        const entries = [...html.matchAll(/<script[^>]*\bsrc="([^"]+)"/g)]
          .map((m) => normalize(join('game', m[1])).split('\\').join('/'))
          .filter((path) => path.startsWith('game/js/'));
        const seen = new Set();
        const queue = [...entries];
        while (queue.length) {
          const path = queue.shift();
          if (seen.has(path) || !existsSync(join(ROOT, path))) continue;
          seen.add(path);
          const body = text(path);
          const specs = [
            ...[...body.matchAll(/^\s*import\s[^'"]*['"]([^'"]+)['"]/gm)].map((m) => m[1]),
            ...[...body.matchAll(/\bimport\(\s*['"]([^'"]+)['"]\s*\)/g)].map((m) => m[1]),
            ...[...body.matchAll(/^\s*export\s+[^'"]*from\s+['"]([^'"]+)['"]/gm)].map((m) => m[1]),
          ];
          for (const spec of specs) {
            // Bare specifiers ('three', 'three/addons/…') are the import map's
            // business, and what it points at is vendored, not ours.
            if (!spec.startsWith('.')) continue;
            const target = rel(resolve(join(ROOT, dirname(path)), spec));
            if (target.startsWith('game/js/')) queue.push(target);
          }
        }
        return GAME_JS.filter((path) => !seen.has(path))
          .map((path) => `${path} is never imported -- delete it or wire it up`);
      });

check('the docs do not point at anything missing',
      'A README that lies is worse than no README: it costs a reader the '
      + 'time to discover it lied.',
      () => {
        const found = [];
        const docs = OURS.filter((path) => path.endsWith('.md'));
        for (const path of docs) {
          const body = text(path);
          const links = [...body.matchAll(/\]\((?!https?:|mailto:|#)([^)]+)\)/g)]
            .map((m) => m[1].split('#')[0].trim())
            .filter(Boolean);
          for (const link of links) {
            const target = normalize(join(dirname(path), link));
            if (!existsSync(join(ROOT, target))) {
              found.push(`${path}: links to ${link}, which does not exist`);
            }
          }
          // Commands are documentation too, and they rot the same way.
          const scripts = Object.keys(JSON.parse(text('package.json')).scripts);
          for (const m of body.matchAll(/npm run ([\w:]+)/g)) {
            if (!scripts.includes(m[1])) {
              found.push(`${path}: documents \`npm run ${m[1]}\`,`
                         + ' which package.json does not define');
            }
          }
        }
        return found;
      });

check('the text is clean',
      'Trailing spaces, tabs and CRLF turn into diff noise that hides the '
      + 'one line that actually changed.',
      () => {
        const found = [];
        const WIDTH = 100;
        // Width is a code rule. Prose wraps where the sentence wants to, and a
        // Markdown table row or a JSON string cannot be broken at all.
        const wraps = (path) => /\.(js|mjs|py|css|html)$/.test(path);
        for (const path of OURS) {
          const body = text(path);
          if (body.includes('\r')) found.push(`${path}: carriage returns`);
          if (body.length && !body.endsWith('\n')) found.push(`${path}: no newline at end of file`);
          body.split('\n').forEach((line, i) => {
            const at = `${path}:${i + 1}`;
            if (/[ \t]$/.test(line)) found.push(`${at}: trailing whitespace`);
            if (/\t/.test(line) && !path.endsWith('.md')) found.push(`${at}: tab`);
            if (wraps(path) && line.length > WIDTH) {
              found.push(`${at}: ${line.length} columns (limit ${WIDTH})`);
            }
          });
        }
        return found;
      });

check('every source file parses',
      'The browser suites take minutes to tell you about a stray bracket. '
      + 'This takes a second.',
      () => {
        const found = [];
        const js = SOURCE.filter((path) => /\.(js|mjs)$/.test(path));
        for (const path of js) {
          // `"type": "module"` in package.json is what makes --check read a
          // bare .js as an ES module rather than as CommonJS.
          const result = spawnQuiet(process.execPath, ['--check', path]);
          if (result) found.push(`${path}: ${result.split('\n').slice(0, 3).join(' ')}`);
        }
        const py = SOURCE.filter((path) => path.endsWith('.py'));
        if (py.length) {
          // compile() rather than py_compile: the latter writes __pycache__
          // directories, and a check that dirties the tree it is checking is
          // no better than the mess it is looking for.
          const result = spawnQuiet('python3', ['-c', PY_PARSE, ...py]);
          if (result) found.push(result.split('\n').slice(0, 4).join(' '));
        }
        for (const path of SOURCE.filter((name) => name.endsWith('.sh'))) {
          const result = spawnQuiet('bash', ['-n', path]);
          if (result) found.push(`${path}: ${result.split('\n').slice(0, 3).join(' ')}`);
        }
        return found;
      });

check('nothing generated or private is tracked',
      'Build output in git is merge conflicts nobody can resolve; a keystore '
      + 'in git is the app, gone.',
      () => {
        const found = [];
        const ignored = execFileSync('git', ['ls-files', '-z', '-i', '-c', '--exclude-standard'],
                                     { cwd: ROOT }).toString().split('\0').filter(Boolean);
        for (const path of ignored) found.push(`${path} is tracked but .gitignore excludes it`);
        const secret = /(\.keystore|\.jks|keystore\.properties|\.env)$/;
        for (const path of FILES) {
          if (secret.test(path)) found.push(`${path} must never be committed`);
        }
        return found;
      });

// --- helpers ----------------------------------------------------------------

/**
 * The translation tables, read out of game/js/i18n.js.
 *
 * Parsed rather than imported: importing it would need a DOM, and the point
 * of this gate is to run without a browser. The file is a plain object
 * literal of single-quoted keys, which is exactly what the rest of the repo
 * writes, so the parse stays honest as long as that holds -- and if it ever
 * stops holding, `tables` comes back empty and every i18n check shouts.
 */
let i18nCache = null;
function i18n() {
  if (i18nCache) return i18nCache;
  const src = text('game/js/i18n.js');
  const tables = {};
  const order = {};
  const codes = [...src.matchAll(/\{\s*code:\s*'(\w+)'/g)].map((m) => m[1]);
  for (const code of codes) {
    const start = src.search(new RegExp(`^  ${code}: \\{$`, 'm'));
    if (start < 0) continue;
    const end = src.indexOf('\n  },', start);
    const body = src.slice(start, end < 0 ? src.length : end);
    const table = {};
    const keys = [];
    // Values may be concatenated across lines: take everything up to the
    // line that starts the next key, or the end of the table.
    const entry = /^\s{4}'([^']+)':\s*([\s\S]*?)(?=\n\s{4}'[^']+':|$)/gm;
    for (const m of body.matchAll(entry)) {
      keys.push(m[1]);
      table[m[1]] = [...m[2].matchAll(/'((?:[^'\\]|\\.)*)'/g)]
        .map((s) => s[1]).join('');
    }
    tables[code] = table;
    order[code] = keys;
  }
  i18nCache = { tables, order };
  return i18nCache;
}

/**
 * Everywhere the game asks for a string.
 *
 * Keys reach `t()` three ways: written out at the call, carried in config as
 * a `nameKey`-style field, or built from a prefix (`t('weather.' + name)`).
 *
 * The two directions need different evidence, so they get different lists.
 * `asked` is only what unmistakably names a key -- a `t()` argument, a
 * `...Key:` field, a `data-i18n` attribute -- because a key that does not
 * exist has to be a real mistake before we call it one. `mentioned` is every
 * string literal in the game, because a key passed through a local helper
 * (`row('records.jobs', …)`) is still a key in use, and calling it dead would
 * delete a string the player can see.
 */
function keyReferences() {
  const asked = [];
  const mentioned = new Set();
  const prefixes = [];
  const table = tableRegion();
  for (const path of GAME_JS) {
    const body = path === 'game/js/i18n.js'
      ? text(path).slice(0, table.start) + text(path).slice(table.end)
      : text(path);
    body.split('\n').forEach((line, i) => {
      const where = `${path}:${i + 1}`;
      for (const m of line.matchAll(/\bt\(\s*'([^']*)'\s*\+/g)) prefixes.push(m[1]);
      for (const m of line.matchAll(/\bfirstTime\(\s*'([^']*)'\s*\+/g)) prefixes.push(m[1]);
      for (const m of line.matchAll(/\bt\(\s*'([^']+)'\s*[,)]/g)) {
        asked.push({ key: m[1], where });
      }
      for (const m of line.matchAll(/\b\w*Key:\s*'([^']+)'/g)) asked.push({ key: m[1], where });
      for (const m of line.matchAll(/'([^']+)'/g)) mentioned.add(m[1]);
    });
  }
  const html = text('game/index.html');
  for (const m of html.matchAll(/data-i18n(?:-html|-aria)?="([^"]+)"/g)) {
    asked.push({ key: m[1], where: 'game/index.html' });
    mentioned.add(m[1]);
  }
  return { asked, mentioned, prefixes };
}

/** Where the STRINGS object starts and ends in i18n.js -- definitions, not uses. */
function tableRegion() {
  const src = text('game/js/i18n.js');
  const start = src.indexOf('const STRINGS = {');
  const end = start < 0 ? -1 : src.indexOf('\n};', start);
  return start < 0 || end < 0 ? { start: 0, end: 0 } : { start, end: end + 3 };
}

/** Parse every path given, write nothing, and say so on the first failure. */
const PY_PARSE = [
  'import sys',
  'for path in sys.argv[1:]:',
  '    with open(path, "rb") as fh:',
  '        compile(fh.read(), path, "exec")',
].join('\n');

/** Run a command; return '' when it succeeds, its complaint when it does not. */
function spawnQuiet(command, args) {
  try {
    execFileSync(command, args, { cwd: ROOT, stdio: 'pipe' });
    return '';
  } catch (err) {
    return ((err.stderr || '') + (err.stdout || '')).toString().trim()
      || `${command} exited ${err.status}`;
  }
}

// --- running ----------------------------------------------------------------

/**
 * Run every check.
 *
 * @returns {Array<{name: string, why: string, ok: boolean, problems: string[]}>}
 */
export function runChecks() {
  return checks.map(({ name, why, run }) => {
    let problems;
    try {
      problems = run();
    } catch (err) {
      problems = [`the check itself failed: ${err.message}`];
    }
    return { name, why, ok: problems.length === 0, problems };
  });
}

/** Repo-relative paths the gate looked at, for the suites to report. */
export function scope() {
  return { files: FILES.length, sources: SOURCE.length, checks: checks.length };
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  const verbose = process.argv.includes('-v') || process.argv.includes('--verbose');
  const results = runChecks();
  let failed = 0;
  for (const result of results) {
    if (result.ok) {
      console.log(`PASS  ${result.name}`);
      if (verbose) console.log(`      ${result.why}`);
      continue;
    }
    failed += 1;
    console.log(`FAIL  ${result.name}`);
    console.log(`      ${result.why}`);
    for (const problem of result.problems.slice(0, 20)) console.log(`      - ${problem}`);
    const extra = result.problems.length - 20;
    if (extra > 0) console.log(`      - ...and ${extra} more`);
  }
  const { files, sources } = scope();
  console.log(failed
    ? `\n${failed} of ${results.length} checks failed (${files} files, ${sources} sources)`
    : `\nall ${results.length} checks passed (${files} files, ${sources} sources)`);
  process.exit(failed ? 1 : 0);
}
