#!/usr/bin/env python3
"""
make_sw.py -- regenerate the service worker's precache list from disk.

Run it after adding or rebuilding assets:

    python3 tools/make_sw.py
    python3 tools/make_sw.py --check   # fail instead of writing, for the gate

Keeping the list generated means the offline cache can never drift out of sync
with what actually shipped, and the cache name changes whenever any file's
content changes, so browsers pick up a new build instead of serving a stale one.

Generated-but-committed files rot silently: edit a module, forget to rerun
this, and returning players keep the old cache forever because its name never
changed. --check is what stops that -- it rebuilds the file in memory and
compares, so the standards gate can fail the build instead of a player finding
out months later.
"""

import hashlib
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GAME = os.path.join(ROOT, 'game')
SKIP_DIRS = {'.git'}
SKIP_NAMES = {'sw.js'}
INCLUDE_EXT = {'.html', '.css', '.js', '.json', '.webmanifest',
               '.glb', '.png', '.svg'}


def collect():
    files = []
    for base, dirs, names in os.walk(GAME):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for name in sorted(names):
            if name in SKIP_NAMES:
                continue
            if os.path.splitext(name)[1].lower() not in INCLUDE_EXT:
                continue
            path = os.path.join(base, name)
            files.append(os.path.relpath(path, GAME).replace(os.sep, '/'))
    return sorted(files)


def fingerprint(files):
    digest = hashlib.sha256()
    for rel in files:
        digest.update(rel.encode())
        with open(os.path.join(GAME, rel), 'rb') as fh:
            digest.update(hashlib.sha256(fh.read()).digest())
    return digest.hexdigest()[:12]


TEMPLATE = '''/**
 * Service worker -- offline play.
 *
 * GENERATED by tools/make_sw.py; do not edit by hand. The cache name carries a
 * hash of every precached file, so a rebuild invalidates the old cache instead
 * of leaving players on a stale mix of new code and old models.
 */

const CACHE = 'dortyol-%(hash)s';
const ASSETS = %(assets)s;

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(ASSETS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Cache-first: everything here is versioned by the cache name above.
  event.respondWith(
    caches.match(request).then((hit) => hit || fetch(request).then((response) => {
      if (response && response.ok && response.type === 'basic') {
        const copy = response.clone();
        caches.open(CACHE).then((cache) => cache.put(request, copy));
      }
      return response;
    }).catch(() => caches.match('index.html')))
  );
});
'''


def render():
    """The service worker this tree should have, as a string."""
    files = collect()
    return files, TEMPLATE % {
        'hash': fingerprint(files),
        'assets': json.dumps(['./'] + files, indent=2),
    }


def main(argv):
    check_only = '--check' in argv[1:]
    files, body = render()
    out = os.path.join(GAME, 'sw.js')
    rel = os.path.relpath(out, ROOT)

    if check_only:
        current = open(out).read() if os.path.exists(out) else ''
        if current == body:
            print('%s: up to date (%d files)' % (rel, len(files)))
            return 0
        print('%s is stale -- run: python3 tools/make_sw.py' % rel)
        return 1

    with open(out, 'w') as fh:
        fh.write(body)
    total = sum(os.path.getsize(os.path.join(GAME, f)) for f in files)
    print('%s: %d files, %.1f MB precached'
          % (rel, len(files), total / 1048576.0))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
