/**
 * Model loading and instancing.
 *
 * Every .glb here was generated by blender/build_all.py, which also wrote
 * manifest.json alongside them: triangle counts, real bounding boxes and the
 * road's lane geometry. The game reads those numbers rather than restating
 * them, so collision sizes always match the art that shipped.
 */

import * as THREE from 'three';
import { GLTFLoader } from '../vendor/three/addons/loaders/GLTFLoader.js';

const MODEL_PATH = 'assets/models/';
const PAINT_MATERIAL = 'CarPaint';

const loader = new GLTFLoader();
const templates = new Map();

export let manifest = null;

export async function loadManifest() {
  const response = await fetch(MODEL_PATH + 'manifest.json');
  if (!response.ok) throw new Error('manifest.json missing');
  manifest = await response.json();
  return manifest;
}

function loadOne(name) {
  return new Promise((resolve, reject) => {
    loader.load(MODEL_PATH + name + '.glb', (gltf) => {
      const root = gltf.scene;
      root.traverse((node) => {
        if (!node.isMesh) return;
        node.castShadow = false;
        node.receiveShadow = false;
        node.frustumCulled = true;
        // Flat-shaded low-poly art: vertex normals are already per-face.
        const materials = Array.isArray(node.material)
          ? node.material : [node.material];
        materials.forEach((material) => {
          if (material) material.flatShading = false;
        });
      });
      templates.set(name, root);
      resolve(root);
    }, undefined, reject);
  });
}

/**
 * @param {string[]} names
 * @param {(done:number,total:number,name:string)=>void} onProgress
 */
export async function loadAll(names, onProgress) {
  let done = 0;
  for (const name of names) {
    await loadOne(name);
    done += 1;
    if (onProgress) onProgress(done, names.length, name);
  }
  return templates;
}

export function has(name) {
  return templates.has(name);
}

/** A fresh scene-graph copy. Geometry and materials stay shared. */
export function instance(name) {
  const template = templates.get(name);
  if (!template) throw new Error('model not loaded: ' + name);
  return template.clone(true);
}

export function info(name) {
  return (manifest && manifest.models && manifest.models[name]) || null;
}

/**
 * Footprint used for collision, shrunk a little so a pass that looks clean
 * is a clean pass. Returns metres in world axes: x = width, z = length.
 */
export function footprint(name, shrink) {
  const entry = info(name);
  if (!entry) return { width: 2, length: 4.4, height: 1.5 };
  return {
    width: entry.size[0] * shrink,
    length: entry.size[1] * shrink,
    height: entry.size[2],
  };
}

/**
 * Recolour one named material slot on a single instance.
 *
 * The template's materials are shared by every clone, so the material is
 * cloned before it is touched -- otherwise repainting one taxi would repaint
 * the whole city.
 */
export function tint(root, slot, color) {
  const wanted = new THREE.Color(color);
  root.traverse((node) => {
    if (!node.isMesh || !node.material) return;
    if (Array.isArray(node.material)) {
      node.material = node.material.map((material) => (
        material && material.name === slot
          ? recolour(material, wanted) : material));
    } else if (node.material.name === slot) {
      node.material = recolour(node.material, wanted);
    }
  });
  return root;
}

/** Recolour a vehicle's paint. */
export function tintPaint(root, color) {
  return tint(root, PAINT_MATERIAL, color);
}

function recolour(material, tint) {
  const copy = material.clone();
  copy.color.copy(tint);
  return copy;
}

/** Wheel nodes, by the names Blender exported. */
export function wheels(root) {
  const found = { front: [], rear: [], all: [] };
  ['FL', 'FR', 'ML', 'MR', 'RL', 'RR'].forEach((tag) => {
    const node = root.getObjectByName('Wheel_' + tag);
    if (!node) return;
    node.rotation.order = 'YXZ';        // steer about Y, then roll about X
    found.all.push(node);
    (tag[0] === 'F' ? found.front : found.rear).push(node);
  });
  return found;
}

/** Dispose an instance's cloned materials when it is thrown away for good. */
export function disposeInstance(root) {
  root.traverse((node) => {
    if (!node.isMesh) return;
    const materials = Array.isArray(node.material)
      ? node.material : [node.material];
    materials.forEach((material) => {
      if (material && material.userData && material.userData.cloned) {
        material.dispose();
      }
    });
  });
}
