import { ItemCategory, Rarity } from './enums.js';

/**
 * Static definition of an item. Instances in a raid or a stash only ever store
 * `{ defId, quantity, ... }` — everything else is looked up here, so balance
 * changes never require a data migration.
 */
export interface ItemDefinition {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly rarity: Rarity;
  readonly category: ItemCategory;
  /** Kilograms. */
  readonly weight: number;
  /** Base vendor buy price in credits. */
  readonly value: number;
  readonly stackSize: number;
  /** Placeholder icon key resolved by the web client (`/game/icons/<icon>.svg`). */
  readonly icon: string;
  /** Grid footprint in inventory cells. */
  readonly width: number;
  readonly height: number;
  readonly questItem: boolean;
  readonly tradable: boolean;
  /** Set for medical items: health restored on use. */
  readonly healAmount?: number;
  /** Set for medical items: seconds the heal takes. */
  readonly useTimeSeconds?: number;
  /** Set for armour: armour points granted when equipped. */
  readonly armorPoints?: number;
  /** Set for keys: id of the locked room this key opens. */
  readonly unlocksRoomId?: string;
  /** Set for ammo: how many rounds a single stack unit represents. */
  readonly roundsPerUnit?: number;
}

function def(d: ItemDefinition): ItemDefinition {
  return d;
}

/**
 * Non-weapon item catalogue. Adding an item here is enough — no gameplay code
 * changes. Weapons contribute their own item entries from `weapons.ts`; both
 * lists are merged into the canonical lookup in `catalog.ts`.
 */
export const BASE_ITEM_DEFINITIONS: readonly ItemDefinition[] = [
  // ---------------------------------------------------------------- crafting
  def({
    id: 'scrap_metal',
    name: 'Scrap Metal',
    description: 'Twisted rebar and plating stripped from the quarantine barricades.',
    rarity: Rarity.Common,
    category: ItemCategory.Crafting,
    weight: 1.2,
    value: 180,
    stackSize: 6,
    icon: 'scrap',
    width: 1,
    height: 1,
    questItem: false,
    tradable: true,
  }),
  def({
    id: 'weapon_parts',
    name: 'Weapon Parts',
    description: 'Springs, pins and a usable bolt carrier. Gunsmiths pay well.',
    rarity: Rarity.Uncommon,
    category: ItemCategory.Crafting,
    weight: 0.9,
    value: 620,
    stackSize: 4,
    icon: 'parts',
    width: 1,
    height: 2,
    questItem: false,
    tradable: true,
  }),
  def({
    id: 'duct_tape',
    name: 'Industrial Tape',
    description: 'Holds the district together. Mostly.',
    rarity: Rarity.Common,
    category: ItemCategory.Crafting,
    weight: 0.3,
    value: 95,
    stackSize: 8,
    icon: 'tape',
    width: 1,
    height: 1,
    questItem: false,
    tradable: true,
  }),

  // ------------------------------------------------------------- electronics
  def({
    id: 'broken_phone',
    name: 'Broken Phone',
    description: 'Cracked screen, intact board. The board is the valuable part.',
    rarity: Rarity.Common,
    category: ItemCategory.Electronics,
    weight: 0.2,
    value: 240,
    stackSize: 4,
    icon: 'phone',
    width: 1,
    height: 1,
    questItem: false,
    tradable: true,
  }),
  def({
    id: 'military_battery',
    name: 'Military Battery',
    description: 'Sealed cell from a field generator. Still holds charge.',
    rarity: Rarity.Rare,
    category: ItemCategory.Electronics,
    weight: 3.4,
    value: 2_400,
    stackSize: 1,
    icon: 'battery',
    width: 2,
    height: 2,
    questItem: false,
    tradable: true,
  }),
  def({
    id: 'encrypted_drive',
    name: 'Encrypted Drive',
    description: 'Quarantine authority data. Someone outside the wall wants this.',
    rarity: Rarity.Epic,
    category: ItemCategory.Electronics,
    weight: 0.4,
    value: 5_800,
    stackSize: 1,
    icon: 'drive',
    width: 1,
    height: 1,
    questItem: true,
    tradable: true,
  }),
  def({
    id: 'experimental_chip',
    name: 'Experimental Chip',
    description: 'Unlabelled silicon from the bunker labs. Warm to the touch.',
    rarity: Rarity.Epic,
    category: ItemCategory.Electronics,
    weight: 0.1,
    value: 8_600,
    stackSize: 1,
    icon: 'chip',
    width: 1,
    height: 1,
    questItem: false,
    tradable: true,
  }),
  def({
    id: 'ai_core',
    name: 'AI Core',
    description: 'The reason Sector Zero was sealed. Do not let it leave your hands.',
    rarity: Rarity.Legendary,
    category: ItemCategory.Electronics,
    weight: 2.1,
    value: 24_000,
    stackSize: 1,
    icon: 'core',
    width: 2,
    height: 2,
    questItem: true,
    tradable: true,
  }),

  // --------------------------------------------------------------- valuables
  def({
    id: 'gold_watch',
    name: 'Gold Watch',
    description: 'Stopped at 04:12, the moment the sirens started.',
    rarity: Rarity.Rare,
    category: ItemCategory.Valuable,
    weight: 0.1,
    value: 3_100,
    stackSize: 2,
    icon: 'watch',
    width: 1,
    height: 1,
    questItem: false,
    tradable: true,
  }),
  def({
    id: 'cash_bundle',
    name: 'Cash Bundle',
    description: 'Pre-quarantine notes. Still spends at the wall.',
    rarity: Rarity.Uncommon,
    category: ItemCategory.Valuable,
    weight: 0.2,
    value: 860,
    stackSize: 5,
    icon: 'cash',
    width: 1,
    height: 1,
    questItem: false,
    tradable: true,
  }),
  def({
    id: 'silver_ingot',
    name: 'Silver Ingot',
    description: 'Looted from the market street vault before the collapse.',
    rarity: Rarity.Rare,
    category: ItemCategory.Valuable,
    weight: 4.8,
    value: 4_200,
    stackSize: 1,
    icon: 'ingot',
    width: 2,
    height: 1,
    questItem: false,
    tradable: true,
  }),

  // ----------------------------------------------------------------- medical
  def({
    id: 'bandage',
    name: 'Field Bandage',
    description: 'Stops the bleeding. Barely.',
    rarity: Rarity.Common,
    category: ItemCategory.Medical,
    weight: 0.1,
    value: 220,
    stackSize: 6,
    icon: 'bandage',
    width: 1,
    height: 1,
    questItem: false,
    tradable: true,
    healAmount: 25,
    useTimeSeconds: 2.2,
  }),
  def({
    id: 'medical_kit',
    name: 'Medical Kit',
    description: 'Compact trauma kit. The difference between MIA and EXTRACTED.',
    rarity: Rarity.Uncommon,
    category: ItemCategory.Medical,
    weight: 1.1,
    value: 1_150,
    stackSize: 2,
    icon: 'medkit',
    width: 2,
    height: 1,
    questItem: false,
    tradable: true,
    healAmount: 60,
    useTimeSeconds: 4,
  }),
  def({
    id: 'combat_stim',
    name: 'Combat Stim',
    description: 'Military-grade adrenaline. Full heal, wrecked hands.',
    rarity: Rarity.Rare,
    category: ItemCategory.Medical,
    weight: 0.2,
    value: 2_600,
    stackSize: 2,
    icon: 'stim',
    width: 1,
    height: 1,
    questItem: false,
    tradable: true,
    healAmount: 100,
    useTimeSeconds: 2.5,
  }),

  // ------------------------------------------------------------------- armor
  def({
    id: 'armor_light_vest',
    name: 'Patrol Vest',
    description: 'Police-issue soft armour. Stops pistol rounds, not much else.',
    rarity: Rarity.Common,
    category: ItemCategory.Armor,
    weight: 3.2,
    value: 1_400,
    stackSize: 1,
    icon: 'vest-light',
    width: 2,
    height: 2,
    questItem: false,
    tradable: true,
    armorPoints: 35,
  }),
  def({
    id: 'armor_tactical_rig',
    name: 'Tactical Rig',
    description: 'Ceramic plates in a scarred nylon carrier.',
    rarity: Rarity.Rare,
    category: ItemCategory.Armor,
    weight: 6.4,
    value: 4_800,
    stackSize: 1,
    icon: 'vest-tactical',
    width: 2,
    height: 2,
    questItem: false,
    tradable: true,
    armorPoints: 70,
  }),
  def({
    id: 'armor_heavy_plate',
    name: 'Breacher Plate',
    description: 'Bunker guard armour. Heavy enough that you hear yourself coming.',
    rarity: Rarity.Epic,
    category: ItemCategory.Armor,
    weight: 11.2,
    value: 9_400,
    stackSize: 1,
    icon: 'vest-heavy',
    width: 2,
    height: 3,
    questItem: false,
    tradable: true,
    armorPoints: 100,
  }),

  // -------------------------------------------------------------------- ammo
  def({
    id: 'ammo_light',
    name: '9mm Rounds',
    description: 'Feeds pistols and SMGs.',
    rarity: Rarity.Common,
    category: ItemCategory.Ammo,
    weight: 0.3,
    value: 120,
    stackSize: 8,
    icon: 'ammo-light',
    width: 1,
    height: 1,
    questItem: false,
    tradable: true,
    roundsPerUnit: 30,
  }),
  def({
    id: 'ammo_medium',
    name: '5.56 Rounds',
    description: 'Standard rifle ammunition.',
    rarity: Rarity.Common,
    category: ItemCategory.Ammo,
    weight: 0.4,
    value: 190,
    stackSize: 8,
    icon: 'ammo-medium',
    width: 1,
    height: 1,
    questItem: false,
    tradable: true,
    roundsPerUnit: 30,
  }),
  def({
    id: 'ammo_heavy',
    name: '7.62 Rounds',
    description: 'Marksman ammunition. Punches through plate.',
    rarity: Rarity.Uncommon,
    category: ItemCategory.Ammo,
    weight: 0.6,
    value: 320,
    stackSize: 6,
    icon: 'ammo-heavy',
    width: 1,
    height: 1,
    questItem: false,
    tradable: true,
    roundsPerUnit: 20,
  }),
  def({
    id: 'ammo_shell',
    name: '12ga Shells',
    description: 'Buckshot. Close work only.',
    rarity: Rarity.Common,
    category: ItemCategory.Ammo,
    weight: 0.5,
    value: 160,
    stackSize: 6,
    icon: 'ammo-shell',
    width: 1,
    height: 1,
    questItem: false,
    tradable: true,
    roundsPerUnit: 18,
  }),

  // -------------------------------------------------------------------- keys
  def({
    id: 'key_police_armory',
    name: 'Police Armory Key',
    description: 'Opens the sealed armoury behind the station front desk.',
    rarity: Rarity.Rare,
    category: ItemCategory.Key,
    weight: 0.05,
    value: 3_400,
    stackSize: 1,
    icon: 'key',
    width: 1,
    height: 1,
    questItem: false,
    tradable: true,
    unlocksRoomId: 'police_armory',
  }),
  def({
    id: 'key_bunker_access',
    name: 'Bunker Keycard',
    description: 'Quarantine authority clearance. The bunker vault answers to it.',
    rarity: Rarity.Epic,
    category: ItemCategory.Key,
    weight: 0.05,
    value: 7_200,
    stackSize: 1,
    icon: 'keycard',
    width: 1,
    height: 1,
    questItem: false,
    tradable: true,
    unlocksRoomId: 'bunker_vault',
  }),
  def({
    id: 'access_card',
    name: 'Access Card',
    description: 'Generic staff card. Traders collect them for the chip inside.',
    rarity: Rarity.Uncommon,
    category: ItemCategory.Quest,
    weight: 0.05,
    value: 740,
    stackSize: 3,
    icon: 'card',
    width: 1,
    height: 1,
    questItem: true,
    tradable: true,
  }),
];
